# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: helloworld.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import helloworld_pb2


class GreeterBase(abc.ABC):

    @abc.abstractmethod
    async def SayHello(self, stream):
        pass

    @abc.abstractmethod
    async def SayHelloAgain(self, stream):
        pass

    def __mapping__(self):
        return {
            '/Greeter/SayHello': grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                helloworld_pb2.HelloRequest,
                helloworld_pb2.HelloReply,
            ),
            '/Greeter/SayHelloAgain': grpclib.const.Handler(
                self.SayHelloAgain,
                grpclib.const.Cardinality.UNARY_UNARY,
                helloworld_pb2.HelloRequest,
                helloworld_pb2.HelloReply,
            ),
        }


class GreeterStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Greeter/SayHello',
            helloworld_pb2.HelloRequest,
            helloworld_pb2.HelloReply,
        )
        self.SayHelloAgain = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Greeter/SayHelloAgain',
            helloworld_pb2.HelloRequest,
            helloworld_pb2.HelloReply,
        )


class InfoBase(abc.ABC):

    @abc.abstractmethod
    async def DisplayInfo(self, stream):
        pass

    def __mapping__(self):
        return {
            '/Info/DisplayInfo': grpclib.const.Handler(
                self.DisplayInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                helloworld_pb2.InfoRequest,
                helloworld_pb2.DispInfo,
            ),
        }


class InfoStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DisplayInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Info/DisplayInfo',
            helloworld_pb2.InfoRequest,
            helloworld_pb2.DispInfo,
        )
